# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/experimental/_join_streams.pyx

from pylibcudf.typing import CudaStreamLike

__all__ = ['join_streams']

def join_streams(streams: list[CudaStreamLike], stream: CudaStreamLike) -> None: ...
