# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/binaryop.pyx

from pylibcudf.libcudf.binaryop import binary_operator
from pylibcudf.libcudf.binaryop import binary_operator as BinaryOperator
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .scalar import Scalar
from .types import DataType

__all__ = ['BinaryOperator', 'binary_operation', 'is_supported_operation']

def binary_operation(lhs: Column | Scalar, rhs: Column | Scalar, op: binary_operator, output_type: DataType, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def is_supported_operation(out: DataType, lhs: DataType, rhs: DataType, op: binary_operator) -> bool: ...
