# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/context.pyx

__all__ = ['clear_jit_cache', 'enable_jit_cache']

def enable_jit_cache(enable: bool) -> None: ...
def clear_jit_cache() -> None: ...
