# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/expressions.pyx

import functools

from pylibcudf.libcudf.expressions import ast_operator
from pylibcudf.libcudf.expressions import ast_operator as ASTOperator
from pylibcudf.libcudf.expressions import table_reference
from pylibcudf.libcudf.expressions import table_reference as TableReference
from pylibcudf.libcudf.types import size_type

from .scalar import Scalar

__all__ = ['ASTOperator', 'ColumnNameReference', 'ColumnReference', 'Expression', 'Literal', 'Operation', 'TableReference', 'to_expression']

class Expression:
    __hash__ = None

class Literal(Expression):
    def __init__(self, value: Scalar): ...

class ColumnReference(Expression):
    def __init__(self, index: size_type, table_source: table_reference=table_reference.LEFT): ...

class Operation(Expression):
    def __init__(self, op: ast_operator, left: Expression, right: Expression | None=None): ...

class ColumnNameReference(Expression):
    def __init__(self, name: str): ...

@functools.lru_cache(256)
def to_expression(expr: str, column_names: tuple[str, ...]) -> Expression: ...
