# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/filling.pyx

from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .scalar import Scalar
from .table import Table

__all__ = ['fill', 'fill_in_place', 'repeat', 'sequence', 'calendrical_month_sequence']

def fill(destination: Column, begin: size_type, end: size_type, value: Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def fill_in_place(destination: Column, begin: size_type, end: size_type, value: Scalar, stream: CudaStreamLike | None=None) -> None: ...
def sequence(size: size_type, init: Scalar, step: Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def repeat(input_table: Table, count: Column | size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table: ...
def calendrical_month_sequence(n: size_type, init: Scalar, months: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
