# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/gpumemoryview.pyx

from collections.abc import Mapping
from typing import Any

import cython

__all__ = ['gpumemoryview']

class gpumemoryview:
    __hash__ = None
    ptr: int
    obj: object
    cai: dict
    nbytes: int

    def __init__(self, obj: Any): ...
    @property
    def __cuda_array_interface__(self) -> Mapping[str, Any]: ...
    @property
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    @cython.annotation_typing(False)
    def byte_slice(self, s: slice) -> gpumemoryview: ...
