# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/interop.pyx

from pylibcudf.table import Table
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from ._interop_helpers import ColumnMetadata

__all__ = ['ColumnMetadata', 'from_dlpack', 'to_dlpack']

def from_dlpack(managed_tensor: object, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table: ...
def to_dlpack(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> object: ...
