# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/labeling.pyx

from pylibcudf.libcudf.labeling import inclusive
from pylibcudf.libcudf.labeling import inclusive as Inclusive
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column

__all__ = ['Inclusive', 'label_bins']

def label_bins(input: Column, left_edges: Column, left_inclusive: inclusive, right_edges: Column, right_inclusive: inclusive, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
