# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/merge.pyx

from pylibcudf.types import NullOrder, Order
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .table import Table

__all__ = ['merge']

def merge(tables_to_merge: list[Table], key_cols: list[int], column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table: ...
