# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/partitioning.pyx

from pylibcudf.libcudf import partitioning as cpp_partitioning
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .table import Table

__all__ = ['hash_partition', 'partition', 'round_robin_partition']

def hash_partition(input: Table, keys: Table | list[int], num_partitions: int, hash_function: cpp_partitioning.hash_id=cpp_partitioning.hash_id.HASH_MURMUR3, seed: int=cpp_partitioning.DEFAULT_HASH_SEED, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple[object, object]: ...
def partition(t: Table, partition_map: Column, num_partitions: int, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple[object, object]: ...
def round_robin_partition(input: Table, num_partitions: int, start_partition: int=0, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple[object, object]: ...
