# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/quantiles.pyx

from collections.abc import Iterable

from pylibcudf.libcudf.types import interpolation, sorted
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .table import Table

__all__ = ['quantile', 'quantiles']

def quantile(input: Column, q: Iterable[float], interp: interpolation=interpolation.LINEAR, ordered_indices: Column | None=None, exact: bool=True, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def quantiles(input: Table, q: Iterable[float], interp: interpolation=interpolation.NEAREST, is_input_sorted: sorted=sorted.NO, column_order: list | None=None, null_precedence: list | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table: ...
