# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/replace.pyx

from pylibcudf.libcudf.replace import replace_policy as ReplacePolicy
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .scalar import Scalar

__all__ = ['ReplacePolicy', 'clamp', 'find_and_replace_all', 'normalize_nans_and_zeros', 'replace_nulls']

def replace_nulls(source_column: Column, replacement: Column | Scalar | ReplacePolicy, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def find_and_replace_all(source_column: Column, values_to_replace: Column, replacement_values: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def clamp(source_column: Column, lo: Scalar, hi: Scalar, lo_replace: Scalar | None=None, hi_replace: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def normalize_nans_and_zeros(source_column: Column, inplace: bool=False, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
