# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/reshape.pyx

from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .table import Table

__all__ = ['interleave_columns', 'tile', 'table_to_array']

def interleave_columns(source_table: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def tile(source_table: Table, count: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table: ...
def table_to_array(input_table: Table, ptr: int, size: int, stream: CudaStreamLike | None=None) -> None: ...
