# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/round.pyx

from pylibcudf.libcudf.round import rounding_method
from pylibcudf.libcudf.round import rounding_method as RoundingMethod
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column

__all__ = ['RoundingMethod', 'round']

def round(source: Column, decimal_places: int=0, round_method: rounding_method=rounding_method.HALF_UP, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def round_decimal(source: Column, decimal_places: int=0, round_method: rounding_method=rounding_method.HALF_UP, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
