# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/scalar.pyx

import datetime
import decimal
from typing import Any, TypeAlias

from cpython import bool as py_bool
from cython import no_gc_clear
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource
from rmm.pylibrmm.stream import Stream

from ._interop_helpers import ArrowLike, ColumnMetadata
from .types import DataType

NpGeneric: TypeAlias = Any
__all__ = ['Scalar']

@no_gc_clear
class Scalar:
    __hash__ = None

    def __init__(self, *args, **kwargs): ...
    def type(self) -> DataType: ...
    def is_valid(self, stream: CudaStreamLike | None=None) -> bool: ...
    def to_arrow(self, metadata: ColumnMetadata | str | None=None, stream: CudaStreamLike | None=None) -> ArrowLike: ...
    @staticmethod
    def from_arrow(pa_val: Any, dtype: DataType | None=None, stream: CudaStreamLike | None=None) -> Scalar: ...
    @classmethod
    def from_py(cls, py_val: Any, dtype: DataType | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Scalar: ...
    @classmethod
    def from_numpy(cls, np_val: NpGeneric, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Scalar: ...
    def to_py(self, stream: CudaStreamLike | None=None) -> None | int | float | str | bool | decimal.Decimal: ...
