# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/search.pyx

from pylibcudf.types import NullOrder, Order
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .table import Table

__all__ = ['contains', 'lower_bound', 'upper_bound']

def lower_bound(haystack: Table, needles: Table, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def upper_bound(haystack: Table, needles: Table, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def contains(haystack: Column, needles: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
