# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/table_equality.pyx

from pylibcudf.libcudf.types import null_equality
from pylibcudf.typing import CudaStreamLike

from .table import Table

__all__ = ['tables_equal']

def tables_equal(left: Table, right: Table, nulls_equal: null_equality=null_equality.EQUAL, stream: CudaStreamLike | None=None) -> bool: ...
