# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/transpose.pyx

from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .table import Table

__all__ = ['transpose']

def transpose(input_table: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table: ...
