# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/types.pyx

from typing import Any, TypeAlias

from pylibcudf.libcudf.types import bitmask_type
from pylibcudf.libcudf.types import interpolation as Interpolation
from pylibcudf.libcudf.types import mask_state as MaskState
from pylibcudf.libcudf.types import nan_equality as NanEquality
from pylibcudf.libcudf.types import nan_policy as NanPolicy
from pylibcudf.libcudf.types import null_aware as NullAware
from pylibcudf.libcudf.types import null_equality as NullEquality
from pylibcudf.libcudf.types import null_order as NullOrder
from pylibcudf.libcudf.types import null_policy as NullPolicy
from pylibcudf.libcudf.types import order as Order
from pylibcudf.libcudf.types import output_nullability as OutputNullability
from pylibcudf.libcudf.types import size_type
from pylibcudf.libcudf.types import sorted as Sorted
from pylibcudf.libcudf.types import type_id
from pylibcudf.libcudf.types import type_id as TypeId
from pylibcudf.libcudf.utilities.type_dispatcher import type_to_id

PyarrowDataType: TypeAlias = Any
__all__ = ['DataType', 'Interpolation', 'MaskState', 'NanEquality', 'NanPolicy', 'NullEquality', 'NullOrder', 'NullAware', 'OutputNullability', 'NullPolicy', 'Order', 'SIZE_TYPE', 'SIZE_TYPE_ID', 'Sorted', 'TypeId', 'size_of']
SIZE_TYPE = DataType(type_to_id[size_type]())
SIZE_TYPE_ID = SIZE_TYPE.id()
BITMASK_TYPE = DataType(type_to_id[bitmask_type]())

class DataType:
    def __init__(self, id: type_id, scale: int=0): ...
    def id(self) -> type_id: ...
    def scale(self) -> int: ...
    @property
    def typestr(self) -> str: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __reduce__(self): ...
    def to_arrow(self, **kwargs) -> PyarrowDataType: ...
    @staticmethod
    def from_arrow(pa_typ: PyarrowDataType) -> DataType: ...
    @staticmethod
    def from_py(typ: type) -> DataType: ...

def size_of(t: DataType) -> int: ...
