# SPDX-FileCopyrightText: Copyright (c) 2019-2025, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/utilities.pyx

__all__ = ['is_ptds_enabled']

def is_ptds_enabled() -> bool: ...
