# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/io/datasource.pyx

__all__ = ['Datasource']

class Datasource:
    __hash__ = None
