# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/io/parquet_io_utils.pyx

from pylibcudf.io.text import ByteRangeInfo
from pylibcudf.io.types import SourceInfo
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['fetch_byte_ranges_to_device', 'fetch_page_index_to_host']

def fetch_byte_ranges_to_device(source_info: SourceInfo, byte_ranges: list, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> list: ...
def fetch_page_index_to_host(source_info: SourceInfo, page_index_range: ByteRangeInfo) -> bytes: ...
