# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from collections.abc import Sequence
from enum import IntEnum

from pylibcudf.io.types import SourceInfo
from pylibcudf.table import Table
from pylibcudf.types import DataType, TypeId
from pylibcudf.utils import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

try:
    from collections.abc import Buffer
except ImportError:
    from typing_extensions import Buffer

__all__ = [
    "ColumnChunk",
    "ColumnChunkMetaData",
    "ColumnChunkStatistics",
    "DecimalType",
    "FieldRepetitionType",
    "FileMetaData",
    "IntType",
    "LogicalType",
    "LogicalTypeId",
    "ParquetColumnSchema",
    "ParquetMetadata",
    "ParquetSchema",
    "PhysicalType",
    "RowGroup",
    "SchemaElement",
    "SortingColumn",
    "TimeType",
    "TimeUnit",
    "TimestampType",
    "read_parquet_column_chunk_bounds",
    "read_parquet_footers",
    "read_parquet_metadata",
]

class ParquetColumnSchema:
    def name(self) -> str: ...
    def num_children(self) -> int: ...
    def child(self, idx: int) -> ParquetColumnSchema: ...
    def children(self) -> list[ParquetColumnSchema]: ...

class ParquetSchema:
    def root(self) -> ParquetColumnSchema: ...
    def column_types(self) -> dict[str, DataType]: ...

class ParquetMetadata:
    def schema(self) -> ParquetSchema: ...
    def num_rows(self) -> int: ...
    def num_rowgroups(self) -> int: ...
    def num_rowgroups_per_file(self) -> list[int]: ...
    def metadata(self) -> dict[str, str]: ...
    def rowgroup_metadata(self) -> list[dict[str, int]]: ...
    def columnchunk_metadata(self) -> dict[str, list[int]]: ...

class FileMetaData:
    @classmethod
    def from_bytes(cls, footer_bytes: Buffer) -> FileMetaData: ...
    @property
    def version(self) -> int: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def created_by(self) -> str: ...
    @property
    def row_groups(self) -> list[RowGroup]: ...
    @property
    def row_group_num_rows(self) -> list[int]: ...
    @property
    def columnchunk_metadata(self) -> dict[str, list[int]]: ...
    @property
    def schema(self) -> list[SchemaElement]: ...

class PhysicalType(IntEnum):
    UNDEFINED = ...
    BOOLEAN = ...
    INT32 = ...
    INT64 = ...
    INT96 = ...
    FLOAT = ...
    DOUBLE = ...
    BYTE_ARRAY = ...
    FIXED_LEN_BYTE_ARRAY = ...

class FieldRepetitionType(IntEnum):
    UNSPECIFIED = ...
    REQUIRED = ...
    OPTIONAL = ...
    REPEATED = ...

class LogicalTypeId(IntEnum):
    UNDEFINED = ...
    STRING = ...
    MAP = ...
    LIST = ...
    ENUM = ...
    DECIMAL = ...
    DATE = ...
    TIME = ...
    TIMESTAMP = ...
    INTEGER = ...
    UNKNOWN = ...
    JSON = ...
    BSON = ...
    VARIANT = ...

class TimeUnit(IntEnum):
    UNDEFINED = ...
    MILLIS = ...
    MICROS = ...
    NANOS = ...

class DecimalType:
    @property
    def scale(self) -> int: ...
    @property
    def precision(self) -> int: ...

class TimeType:
    @property
    def is_adjusted_to_utc(self) -> bool: ...
    @property
    def unit(self) -> TimeUnit: ...

class TimestampType:
    @property
    def is_adjusted_to_utc(self) -> bool: ...
    @property
    def unit(self) -> TimeUnit: ...

class IntType:
    @property
    def bit_width(self) -> int: ...
    @property
    def is_signed(self) -> bool: ...

class LogicalType:
    @property
    def type(self) -> LogicalTypeId: ...
    @property
    def decimal_type(self) -> DecimalType | None: ...
    @property
    def time_type(self) -> TimeType | None: ...
    @property
    def timestamp_type(self) -> TimestampType | None: ...
    @property
    def int_type(self) -> IntType | None: ...

class SchemaElement:
    @property
    def name(self) -> str: ...
    @property
    def num_children(self) -> int: ...
    @property
    def field_id(self) -> int | None: ...
    @property
    def type(self) -> PhysicalType: ...
    @property
    def type_length(self) -> int: ...
    @property
    def logical_type(self) -> LogicalType | None: ...
    @property
    def repetition_type(self) -> FieldRepetitionType: ...
    @property
    def output_as_byte_array(self) -> bool: ...
    @property
    def arrow_type(self) -> TypeId | None: ...
    @property
    def max_definition_level(self) -> int: ...
    @property
    def max_repetition_level(self) -> int: ...
    @property
    def parent_idx(self) -> int: ...
    @property
    def children_idx(self) -> list[int]: ...
    def is_stub(self) -> bool: ...
    def is_one_level_list(self, parent: SchemaElement) -> bool: ...
    def is_struct(self) -> bool: ...

class SortingColumn:
    @property
    def column_idx(self) -> int: ...
    @property
    def descending(self) -> bool: ...
    @property
    def nulls_first(self) -> bool: ...

class ColumnChunk:
    @property
    def file_path(self) -> str: ...
    @property
    def file_offset(self) -> int: ...
    @property
    def offset_index_offset(self) -> int: ...
    @property
    def offset_index_length(self) -> int: ...
    @property
    def column_index_offset(self) -> int: ...
    @property
    def column_index_length(self) -> int: ...
    @property
    def schema_idx(self) -> int: ...
    @property
    def meta_data(self) -> ColumnChunkMetaData: ...

class ColumnChunkStatistics:
    @property
    def has_min_max(self) -> bool: ...
    @property
    def min_encoded(self) -> bytes | None: ...
    @property
    def max_encoded(self) -> bytes | None: ...
    @property
    def null_count(self) -> int | None: ...
    @property
    def distinct_count(self) -> int | None: ...
    @property
    def is_min_value_exact(self) -> bool | None: ...
    @property
    def is_max_value_exact(self) -> bool | None: ...

class ColumnChunkMetaData:
    @property
    def path_in_schema(self) -> list[str]: ...
    @property
    def num_values(self) -> int: ...
    @property
    def total_uncompressed_size(self) -> int: ...
    @property
    def total_compressed_size(self) -> int: ...
    @property
    def statistics(self) -> ColumnChunkStatistics: ...

class RowGroup:
    @property
    def columns(self) -> list[ColumnChunk]: ...
    @property
    def total_byte_size(self) -> int: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def sorting_columns(self) -> list[SortingColumn] | None: ...
    @property
    def file_offset(self) -> int | None: ...
    @property
    def total_compressed_size(self) -> int | None: ...
    @property
    def ordinal(self) -> int | None: ...

def read_parquet_metadata(src_info: SourceInfo) -> ParquetMetadata: ...
def read_parquet_footers(src_info: SourceInfo) -> list[FileMetaData]: ...
def read_parquet_column_chunk_bounds(
    file_metadatas: Sequence[FileMetaData],
    columns: Sequence[str],
    stream: CudaStreamLike | None = None,
    mr: DeviceMemoryResource | None = None,
) -> Table: ...
