# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/io/timezone.pyx

from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from ..table import Table

__all__ = ['make_timezone_transition_table']

def make_timezone_transition_table(tzif_dir: str, timezone_name: str, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table: ...
