# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/capitalize.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.strings.char_types import string_character_types
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['capitalize', 'is_title', 'title']

def capitalize(input: Column, delimiters: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def title(input: Column, sequence_type: string_character_types=string_character_types.ALPHA, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def is_title(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
