# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/char_types.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.strings.char_types import string_character_types
from pylibcudf.libcudf.strings.char_types import \
    string_character_types as StringCharacterTypes
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['StringCharacterTypes', 'all_characters_of_type', 'filter_characters_of_type']

def all_characters_of_type(source_strings: Column, types: string_character_types, verify_types: string_character_types, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def filter_characters_of_type(source_strings: Column, types_to_remove: string_character_types, replacement: Scalar, types_to_keep: string_character_types, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
