# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/combine.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.strings.combine import output_if_empty_list
from pylibcudf.libcudf.strings.combine import \
    output_if_empty_list as OutputIfEmptyList
from pylibcudf.libcudf.strings.combine import separator_on_nulls
from pylibcudf.libcudf.strings.combine import \
    separator_on_nulls as SeparatorOnNulls
from pylibcudf.scalar import Scalar
from pylibcudf.table import Table
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['OutputIfEmptyList', 'SeparatorOnNulls', 'concatenate', 'join_list_elements', 'join_strings']

def concatenate(strings_columns: Table, separator: Column | Scalar, narep: Scalar | None=None, col_narep: Scalar | None=None, separate_nulls: separator_on_nulls=separator_on_nulls.YES, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def join_strings(input: Column, separator: Scalar, narep: Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def join_list_elements(lists_strings_column: Column, separator: Column | Scalar, separator_narep: Scalar, string_narep: Scalar, separate_nulls: separator_on_nulls, empty_list_policy: output_if_empty_list, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
