# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/extract.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.strings.regex_program import RegexProgram
from pylibcudf.table import Table
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['extract', 'extract_all_record', 'extract_single']

def extract(input: Column, prog: RegexProgram, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table: ...
def extract_all_record(input: Column, prog: RegexProgram, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def extract_single(input: Column, prog: RegexProgram, group: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
