# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/findall.pyx

from pylibcudf.column import Column
from pylibcudf.strings.regex_program import RegexProgram
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['findall', 'find_re']

def findall(input: Column, pattern: RegexProgram, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def find_re(input: Column, pattern: RegexProgram, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
