# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/find.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['contains', 'ends_with', 'find', 'rfind', 'starts_with']

def find(input: Column, target: Column | Scalar, start: size_type=0, stop: size_type=-1, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def rfind(input: Column, target: Scalar, start: size_type=0, stop: size_type=-1, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def contains(input: Column, target: Column | Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def starts_with(input: Column, target: Column | Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def ends_with(input: Column, target: Column | Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
