# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/find_multiple.pyx

from pylibcudf.column import Column
from pylibcudf.table import Table
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['find_multiple', 'contains_multiple']

def find_multiple(input: Column, targets: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def contains_multiple(input: Column, targets: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table: ...
