# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/padding.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.strings.side_type import side_type
from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['pad', 'zfill', 'zfill_by_widths']

def pad(input: Column, width: size_type, side: side_type, fill_char: str, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def zfill(input: Column, width: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def zfill_by_widths(input: Column, widths: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
