# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/regex_program.pyx

from pylibcudf.libcudf.strings.regex_flags import regex_flags

__all__ = ['RegexProgram']

class RegexProgram:
    __hash__ = None

    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(pattern: str, flags: regex_flags) -> RegexProgram: ...
