# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/replace_re.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.scalar import Scalar
from pylibcudf.strings.regex_program import RegexProgram
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['replace_re', 'replace_with_backrefs']

def replace_re(input: Column, pattern: RegexProgram, replacement: Scalar | None=None, max_replace_count: size_type=-1, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def replace_with_backrefs(input: Column, prog: RegexProgram, replacement: str, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
