# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/slice.pyx

from typing import TypeVar

from pylibcudf.column import Column
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

ColumnOrScalar = TypeVar('ColumnOrScalar', Column, Scalar)
__all__ = ['slice_strings']

def slice_strings(input: Column, start: ColumnOrScalar | None=None, stop: ColumnOrScalar | None=None, step: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
