# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/translate.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.strings.translate import filter_type
from pylibcudf.libcudf.strings.translate import filter_type as FilterType
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['FilterType', 'filter_characters', 'translate']

def translate(input: Column, chars_table: dict[int | str, int | str], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def filter_characters(input: Column, characters_to_filter: dict[int | str, int | str], keep_characters: filter_type, replacement: Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
