# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/byte_pair_encode.pyx

from pylibcudf.column import Column
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['BPEMergePairs', 'byte_pair_encoding']

class BPEMergePairs:
    __hash__ = None

    def __init__(self, merge_pairs: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None): ...

def byte_pair_encoding(input: Column, merge_pairs: BPEMergePairs, separator: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
