# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/generate_ngrams.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['generate_ngrams', 'generate_character_ngrams', 'hash_character_ngrams']

def generate_ngrams(input: Column, ngrams: size_type, separator: Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def generate_character_ngrams(input: Column, ngrams: size_type=2, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def hash_character_ngrams(input: Column, ngrams: size_type, seed: int, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
