# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/minhash.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['minhash', 'minhash64', 'minhash_ngrams', 'minhash64_ngrams']

def minhash(input: Column, seed: int, a: Column, b: Column, width: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def minhash64(input: Column, seed: int, a: Column, b: Column, width: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def minhash_ngrams(input: Column, ngrams: size_type, seed: int, a: Column, b: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def minhash64_ngrams(input: Column, ngrams: size_type, seed: int, a: Column, b: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
