# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/normalize.pyx

from pylibcudf.column import Column
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['CharacterNormalizernormalize_characters', 'normalize_spaces']

class CharacterNormalizer:
    __hash__ = None

    def __init__(self, do_lower_case: bool, tokens: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None): ...

def normalize_spaces(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def normalize_characters(input: Column, normalizer: CharacterNormalizer, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
