# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/replace.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['filter_tokens', 'replace_tokens']

def replace_tokens(input: Column, targets: Column, replacements: Column, delimiter: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def filter_tokens(input: Column, min_token_length: size_type, replacement: Scalar | None=None, delimiter: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
