# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/stemmer.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.nvtext.stemmer import letter_type as LetterType
from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['is_letter', 'porter_stemmer_measure', 'LetterType']

def is_letter(input: Column, check_vowels: bool, indices: Column | size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def porter_stemmer_measure(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
