# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/wordpiece_tokenize.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['WordPieceVocabulary', 'wordpiece_tokenize']

class WordPieceVocabulary:
    __hash__ = None

    def __init__(self, vocab: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None): ...

def wordpiece_tokenize(input: Column, vocabulary: WordPieceVocabulary, max_words_per_row: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
