# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/convert/convert_floats.pyx

from pylibcudf.column import Column
from pylibcudf.types import DataType
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['from_floats', 'is_float', 'to_floats']

def to_floats(strings: Column, output_type: DataType, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def from_floats(floats: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def is_float(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
