# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/convert/convert_durations.pyx

from pylibcudf.column import Column
from pylibcudf.types import DataType
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['from_durations', 'to_durations']

def to_durations(input: Column, duration_type: DataType, format: str, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def from_durations(durations: Column, format: str | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
